language: python
python:
  - "3.5"
  - "3.6"
# command to run tests
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - unittest.main # or py.test for Python versions 3.5 and below
